# site settings
title: Glen Gratz
subtitle:
email: nicegg@yahoo.com
description: Chessmaster // Father // Techie
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://glengratz.com" # the base hostname & protocol for your site
author: Miles Gratz
street_address:
city: Rockford
state: IL
zip_code:
country: USA
phone: (815) 569-2211

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed